DB_HOST = "localhost"
DB_PORT = 28015

DB_NAME = "particle"
LOG_TABLE_NAME = "logs"
EVT_TABLE_NAME = "events"

DEVICE_ID_FIELD = "coreid"
EVENT_NAME_FIELD = "event"

MONITOR_PORT = 8081

ACCESS_TOKEN = "CHANGE_THIS"
